
name: main-build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: create ArtifactStagingDirectory folder
      run: mkdir drop

    - name: Generate az-func-as-a-graph diagram of DurableFunctionsMonitor.DotNetBackend
      uses: scale-tone/az-func-as-a-graph@github-action-v1.3
      with:
        repoName: microsoft/DurableFunctionsMonitor
        projectFolder: durablefunctionsmonitor.dotnetbackend
        outputFile: drop/DurableFunctionsMonitor-DotNetBackend-Diagram.htm
        
    - name: publish artifacts
      uses: actions/upload-artifact@v4.1.0
      with:
        path: drop

